name: "VOICEVOX Engine Addon (Dev)"
version: "1.2.0-b1"
slug: "voicevox_engine_addon"
description: "VOICEVOX Engine for Home Assistant"
url: https://github.com/taikun114/Home-Assistant-VOICEVOX-Engine/tree/dev
init: false
startup: "services"
arch:
  - "aarch64"
  - "amd64"
boot: "auto"
image: taikun114/voicevox_engine_addon-{arch}
ports:
  "50021/tcp": 50021
webui: "http://[HOST]:[PORT:50021]"
stage: experimental
options:
  cpu_threads: 0
  use_max_cpu_threads: false
  allow_origin: []
  cors_policy: localapps
schema:
  cpu_threads: int(0,)
  use_max_cpu_threads: bool
  allow_origin:
    - str
  cors_policy: list(localapps|all)
